### ISSUE TITLE
Encapsulate plane rotation

### ISSUE THREAD

**Issue by jhabriel** [nidtec-una/krysbas-dev#30]
QR rotation block must be encapsulated, i.e., lines 299 - 316.

**Consider first whether the built-in function can be used**

```Matlab

[R, g] = plane_rotations(H, beta)

% H: Upper Hessenberg matrix (this is an m+1-by-m matrix)
% beta: Norm of the residual (scalar)
% R: Upper triangular matrix (m-by-m)
% g: *decide on name* (m-by-1)

```

**Comment by gusespinola** [comment]
There is a recommendation for this encapsulation in the wiki for GMRES.

https://en.wikipedia.org/wiki/Generalized_minimal_residual_method
