### ISSUE TITLE
Tests for identity matrix are failing

### ISSUE THREAD

**Issue by gusespinola** [nidtec-una/krysbas-dev#66]
Greetings! I am trying to put the GMRES-E algorithm back on track, but I am dealing with bugs when trying to solving the toy linear system

eye(n) * x = ones(n, 1)

The failures are in `test_gmres_e/test_outputs_unrestarted_identity_matrix` and `test_outputs_restarted_identity_matrix`.

Could you please check what would be the expected solution? Thanks in advance!

**Comment by jhabriel** [comment]
I noticed that the branch is 20 commits behind the main branch. Can you try merging the `main` branch into `63-gmres-e` and then we take it from there?

**Comment by jhabriel** [comment]
I believe I solved this issue. It was relate to a `too many input arguments` situation. However, I encountered another unexpected behaviour, which I reported in #68. We need to address that error before merging this solver.
